// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7cjf6B5OrtxeOMY-TpanLr091mwhct-c',
    appId: '1:256520069630:web:f8c6fa7de513cfd25c20af',
    messagingSenderId: '256520069630',
    projectId: 'crypto-coins-list-128',
    authDomain: 'crypto-coins-list-128.firebaseapp.com',
    storageBucket: 'crypto-coins-list-128.firebasestorage.app',
    measurementId: 'G-WGJHJ1QLH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-JZmC_pmUX4LNISK7bENo6iRMn43kXU',
    appId: '1:256520069630:android:fe0b20f414afd6fd5c20af',
    messagingSenderId: '256520069630',
    projectId: 'crypto-coins-list-128',
    storageBucket: 'crypto-coins-list-128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfnKPUjgA6JorRVAyaQRUHlZUe22oLESs',
    appId: '1:256520069630:ios:bd967b9de39feee15c20af',
    messagingSenderId: '256520069630',
    projectId: 'crypto-coins-list-128',
    storageBucket: 'crypto-coins-list-128.firebasestorage.app',
    iosBundleId: 'com.crypto.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfnKPUjgA6JorRVAyaQRUHlZUe22oLESs',
    appId: '1:256520069630:ios:bd967b9de39feee15c20af',
    messagingSenderId: '256520069630',
    projectId: 'crypto-coins-list-128',
    storageBucket: 'crypto-coins-list-128.firebasestorage.app',
    iosBundleId: 'com.crypto.cryptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7cjf6B5OrtxeOMY-TpanLr091mwhct-c',
    appId: '1:256520069630:web:3c1fd5ca0ebb9f745c20af',
    messagingSenderId: '256520069630',
    projectId: 'crypto-coins-list-128',
    authDomain: 'crypto-coins-list-128.firebaseapp.com',
    storageBucket: 'crypto-coins-list-128.firebasestorage.app',
    measurementId: 'G-78NP83TR64',
  );
}
